# Site settings
title: Jina Jeong, 4th Backend Developer
description: Portfolio by Jina Jeong
# baseurl: "/jj-a" # the subpath of your site, e.g. /blog
# url: "jj-a.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jina Jeong
username_kr: 정진아
user_description:
  <p>저는 Process Mining 소프트웨어 개발의 백엔드 엔지니어로 약 4년(3년 9개월)간 일했습니다.</p>
  <h3>흥미로운 사실</h3>
  <ul class="interesting-things">
    <li>대용량 데이터가 포함된 NoSQL (ElasticSearch) 기반 서비스를 대용량 데이터에 최적화된 RDB로 마이그레이션한 경험이 있습니다.</li>
    <li>일반 OOP 어플리케이션을 DDD 구조의 마이크로 서비스 어플리케이션으로 재개발하는 프로젝트에 참여하였고 초기 구조 설계를 맡았으며, 그 중 대용량 데이터 집계 관련 기능을 제공하는 어플리케이션의 리드 개발을 담당하였습니다.</li>
    <li>대용량 데이터로 유의미한 분석을 하는 SQL을 많이 작성했고, 이를 서비스에 녹여내는 데 주력했습니다.</li>
    <li>DB는 ClickHouse(https://clickhouse.com/clickhouse)를 주로 사용했지만 여러 유사 RDB 경험이 있고, 국내에서 다소 마이너한 DB였기 때문에 특정 스택에 국한되지 않고 적응할 수 있는 능력이 생겼습니다😂</li>
  </ul>
user_title: Backend Developer (4th)
email: jxxbom@gmail.com
phone: +82 010-4578-9041
twitter_username: 
github_username: jj-a
gplus_username:  
blog: d-e-v.tistory.com


cover_letter:
  <p>4년 전 신입 개발자로 지원할 때 자기소개엔 이런 말들을 써넣었습니다.</p>
  <p>가장 좋아하는 문장은 루이스 캐럴(Lewis Carrol)의 <거울 나라의 앨리스>에 등장하는 붉은 여왕(Red Queen)의 대사 ─ ‘여기서는 힘껏 달려야 제자리야, 나무를 벗어나려면 지금보다 두 배는 더 빨리 달려야 해.’</p>
  <p>4년 남짓 되는 시간을 한 회사에서 보내고 신입 시절을 지나 중급 개발자의 역량을 조금씩 갖추게 되면서 저의 근본적인 성향은 바뀌지 않았지만 개발자로서의 태도가 조금 달라진 것 같습니다. 예를 들면, 주어진 환경에 비해 스스로의 역량이 부족하다고 느껴 혼자 머리를 싸매고 빨리 나아가고자 행동하는 것이 줄었습니다. 팀(혹은 회사)은 개개인의 단거리 경주하는 자리가 아니니까요.<br>
  또한 ‘개발자는 이래야 해’ 라는 사고방식에서 많이 벗어났습니다. 출발선에서는 모두 내가 얼마나 뛰어난 개발자의 역량을 갖추고 있는지를 증명해야 하기 때문에 저도 마찬가지로 개발자스럽지 않은 제 자신은 숨기고 개발자스러운 저만을 앞세워 억지로 맞지 않는 옷을 입기도 했습니다. 팀 프로젝트들을 수행하면서 의견들이 부딪히고 더 나은 방향을 찾아나가는 과정들을 겪고 나니 ‘얼마나 개발자의 스킬을 잘 쓰는지’도 중요할 수 있지만 ‘어떤 성향의 조합으로 팀원이 이뤄지는지’ 가 꽤나 중요하다는 것을 깨달았습니다. 각자의 강점이 다 다르다는 것도요.</p>
  <p>저는 데이터를 다루는 것을 좋아하는 백엔드 개발자입니다. 아이러니하게도 어릴 때부터 숫자에는 약해서 아직도 수학이 어렵지만, 무언가를 분류하거나 계획을 세우는 것, 객체를 정의하는 것, 역할을 나누는 것을 참 좋아하는 개발자입니다. 코딩 시 효율적인 방법이나 간결한 문법에 대해 많이 고민하는 편이예요.<br>
  또한 약간의 정리벽이 있어서 문서화하는 것을 좋아합니다. 간혹 아직도 손코딩을 하기도 하고요.<br>
  만약 누군가 저에게 무언가에 대해 질문을 한다면, 저는 아마 장문의 답변, 혹은 잘 정리된 문서와 보는 방법을 첨부해줄 거예요.<br>
  맡은 일에 집요한 편이라 간혹 무리를 하기도 하지만 대체로 일과 여가생활의 밸런스를 맞추는 것이 중요하다고 생각합니다. 마라톤 처럼요.</p>
  <p>직장 밖의 저는 책과 미술 전시, 예쁜 카페 탐방을 참 좋아합니다.<br>
  ‘만약에~’ 로 시작하는 상상으로 시작하여 추론하는 것도 좋아해요. 예를 들면, 내가 만약 개발자가 아니라 클라이언트라면 이러한 흐름을 이해할 수 있을까? 처럼요. 다른 사람보다 행동이 조금 느리다는 말을 많이 듣지만 그만큼 꼼꼼하고 신중한 편입니다.<br>
  개발자의 프로필에 다소 어울리지 않는 부분도 많지만 그러한 부분들이 저를 다채로운 사람으로 만듦으로써 좀더 유연한 개발자로 사고할 수 있게 만드는 것 같습니다.</p>
  <p>아직도 배울 것이 많은 개발자입니다. 하지만 저의 강점 또한 분명 팀 여러분들의 능력과 함께 시너지를 발할 수 있을 것이라고 생각합니다.

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
